apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-busy
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-busy
  template:
    metadata:
      labels:
        app: nginx-busy
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 25m
              memory: 8Mi
            limits:
              cpu: 150m
              memory: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-busy
  namespace: default
spec:
  selector:
    app: nginx-busy
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-idle
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-idle
  template:
    metadata:
      labels:
        app: nginx-idle
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 25m
              memory: 8Mi
            limits:
              cpu: 150m
              memory: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-idle
  namespace: default
spec:
  selector:
    app: nginx-idle
  ports:
    - port: 80
      targetPort: 80
